name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTIFY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - run: docker build --platform=linux/amd64 --tag ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}:latest -f ./apps/api/Dockerfile .
      - run: docker push ${{ secrets.GOOGLE_ARTIFACT_REGISTRY }}:latest
